SELECT 
BOLUM_ADI AS BOLUM,
TEZGAH_ADI AS MAKINA, 
KAYIT_TARIH AS DURUS_TARIHI, 
VARDIYA, DURUS_SAATI,
DURUS_SURESI AS DURUS_DK,DURUS_NEDENI,
DIGER_NEDEN AS EKSTRA_NEDEN,
CHARINDEX('-',DURUS_NEDENI) AS SIRA


FROM BTDEL.DBO.DURUS_BASLIK
 JOIN BTDEL.DBO.URETIM_TEZGAH 
ON TEZGAH_NUM= TEZGAH_ID 
 JOIN URETIM_BOLUM 
ON URT_BLM_NUM=BOLUM_NUM

 JOIN BTDEL.DBO.DURUSLAR
ON DURUS_SEQ=BASLIK_ID

ORDER BY KAYIT_TARIH DESC

SELECT DISTINCT TEZGAH_ADI,CONVERT(DECIMAL(6,2),CAST(SUM(DURUS_SURESI) AS  int)/60) AS SAAT ,sum(DURUS_SURESI)%60 AS DK 

FROM BTDEL.DBO.DURUS_BASLIK
INNER JOIN BTDEL.DBO.URETIM_TEZGAH 
ON TEZGAH_NUM= TEZGAH_ID 
INNER JOIN URETIM_BOLUM 
ON URT_BLM_NUM=BOLUM_NUM

INNER JOIN BTDEL.DBO.DURUSLAR
ON DURUS_SEQ=BASLIK_ID

GROUP BY TEZGAH_ADI
ORDER BY SAAT DESC

SELECT DISTINCT DURUS_NEDENI,SUM(DURUS_SURESI) AS SURE,CAST(SUM(DURUS_SURESI) AS  int)/60 AS SAAT ,sum(DURUS_SURESI)%60 AS DK
	FROM BTDEL.DBO.DURUS_BASLIK
	INNER JOIN BTDEL.DBO.URETIM_TEZGAH 
	ON TEZGAH_NUM= TEZGAH_ID 
	INNER JOIN URETIM_BOLUM 
	ON URT_BLM_NUM=BOLUM_NUM
	INNER JOIN BTDEL.DBO.DURUSLAR
	ON DURUS_SEQ=BASLIK_ID

WHERE DURUS_NEDENI <> '' --AND TEZGAH_ADI ='BOTTERO MAKINA KESIM-2' 


GROUP BY DURUS_NEDENI
ORDER BY 2 DESC

--SELECT DURUS_NEDENI,SUM(DURUS_SURESI)


--FROM BTDEL.DBO.DURUS_BASLIK
--INNER JOIN BTDEL.DBO.URETIM_TEZGAH 
--ON TEZGAH_NUM= TEZGAH_ID 
--INNER JOIN URETIM_BOLUM 
--ON URT_BLM_NUM=BOLUM_NUM

--INNER JOIN BTDEL.DBO.DURUSLAR
--ON DURUS_SEQ=BASLIK_ID

--GROUP BY DURUS_NEDENI